### ISSUE TITLE
0.0.z not compatible with 0.0.z+1

### ISSUE THREAD

**Issue by steveklabnik** [dtolnay/semver#106] opened 2017-02-22 15:02 UTC
@eddyb brought this up in `#rust-internals` today. If `y != 0`, any `z` is compatible, but if `y == 0`, they're not. This feels wrong.

I haven't reproduced yet, though.

**Comment by lfairy** [comment] 2017-09-19 08:13
Having `0.0.z` not compatible with `0.0.(z+1)` is [consistent with npm](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004).

**Comment by eddyb** [comment] 2017-09-19 08:37
In that case we should discourage publishing these or ban it fully. `0.0.x` is useless because you simply can't give users a fix if a bug was discovered.

**Comment by kentfredric** [comment] 2020-03-06 09:18
> `0.0.x` is useless because you simply can't give users a fix if a bug was discovered.

My impression that there's a good intention behind this, as 0.x is "unstable", and 0.0.x is "ultra unstable".

Subsequently, I think the use for 0.0.x is for people who are still rapidly changing their project early in the development cycle, where there should be no expectation of inter-compatibility.

Just the communication around this isn't loud enough, so people may either mis-use this version range for their published crates when they aught to migrate to `0.(>=1).*`.

And further, people depend on 0.0.x crates expecting some degree of stability that isn't there, and people depending on 0.0.x should *not* expect to receive updates, as any updates are likely to also come with API breaking changes.

Sure, as-is, it is surprising behaviour, but the surprise comes from a missmatch between what you've learned and what is true.

I'd probably argue in favour of better warnings or documentation regarding the use of 0.0.x ( both in publishing the package, and in the consumption of the package ), than argue 0.0.x to be banned outright.

( It would be especially useful if you're developing a small gaggle of interdependent crates, and rapidly changing their APIs, being able to develop and test them efficiently via cargo, without being forced to promise users a support level you're not ready for )

**Comment by eddyb** [comment] 2020-03-06 11:41
> And further, people depend on 0.0.x crates expecting some degree of stability that isn't there, and people depending on 0.0.x should not expect to receive updates, as any updates are likely to also come with API breaking changes.

The problem isn't in normal usage, but when a `0.0.x` crate has a bug that can be fixed with a backwards-compat release, except there's nothing like `0.0.x.1` to actually release it as.

This could even be a Rust soundness bug which can only be fixed with a breaking change in the compiler, so being able to release fixed versions of crates can be useful.

> Subsequently, I think the use for 0.0.x is for people who are still rapidly changing their project early in the development cycle, where there should be no expectation of inter-compatibility.

You can use `0.x` in *exactly the same way*. `0.0.x` is redundant with that, but is strictly worse because you can't release a patch when other crates (inevitably) depend on yours.

**Comment by dtolnay** [comment] 2021-05-25 19:43
I believe the current behavior matches the description of caret requirements in https://github.com/semver/semver/blob/efcff2c838c9945f79bfd21c1df0073271bcc29c/ranges.md, and matches Cargo's intended behavior, so I'll go ahead and close this.

**Closed by dtolnay** 2021-05-25 19:43 UTC
Labels: bug

**Comment by CobaltCause** [comment] 2025-09-27 04:08
Hmm, I'm not sure it does match Cargo's intended behavior, if you take its documentation to describe its intended behavior rather than its code: https://github.com/rust-lang/cargo/issues/16015
